# Generated by Django 5.1.6 on 2025-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('club_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
    ]
